// Generated by CoffeeScript 1.9.2

/*
API wrapper for beerstyles endpoint

@author Torstein Thune
@copyright Microbrew.it 2015
 */

(function() {
  var BeerStyles, ItemEndpoint,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  ItemEndpoint = require('./ItemEndpoint.coffee');

  BeerStyles = (function(superClass) {
    extend(BeerStyles, superClass);

    function BeerStyles() {
      return BeerStyles.__super__.constructor.apply(this, arguments);
    }

    BeerStyles.prototype.endpoint = 'beerstyles';

    return BeerStyles;

  })(ItemEndpoint);

  module.exports = BeerStyles;

}).call(this);
