// Generated by CoffeeScript 1.9.2

/*
API wrapper for beerstyles endpoint

@author Torstein Thune
@copyright Microbrew.it 2015
 */

(function() {
  var Beers, ItemEndpoint,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  ItemEndpoint = require('./ItemEndpoint.coffee');

  Beers = (function(superClass) {
    extend(Beers, superClass);

    function Beers() {
      return Beers.__super__.constructor.apply(this, arguments);
    }

    Beers.prototype.endpoint = 'beers';

    Beers.prototype.user = function(query, callback, token) {
      return callback(new Error('Not implemented'));
    };

    Beers.prototype.beerxml = function(xml, callback, token) {
      return callback(new Error('Not implemented'));
    };

    return Beers;

  })(ItemEndpoint);

  module.exports = Beers;

}).call(this);
