// Generated by CoffeeScript 1.10.0

/*
API wrapper for glasses endpoint

@author Torstein Thune
@copyright Microbrew.it 2015
 */

(function() {
  var Glasses, ItemEndpoint,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  ItemEndpoint = require('./ItemEndpoint');

  Glasses = (function(superClass) {
    extend(Glasses, superClass);

    function Glasses() {
      return Glasses.__super__.constructor.apply(this, arguments);
    }

    Glasses.prototype.endpoint = 'glasses';

    return Glasses;

  })(ItemEndpoint);

  module.exports = Glasses;

}).call(this);
