// Generated by CoffeeScript 1.9.2

/*
API wrapper for hops endpoint

@author Torstein Thune
@copyright Microbrew.it 2015
 */

(function() {
  var Hops, ItemEndpoint,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  ItemEndpoint = require('./ItemEndpoint.coffee');

  Hops = (function(superClass) {
    extend(Hops, superClass);

    function Hops() {
      return Hops.__super__.constructor.apply(this, arguments);
    }

    Hops.prototype.endpoint = 'hops';

    return Hops;

  })(ItemEndpoint);

  module.exports = Hops;

}).call(this);
