// Generated by CoffeeScript 1.9.2

/*
HTTP class 

This class is extended by the other API classes. Contains basic implementations of get, post, put and delete plus some utility functions.

@author Torstein Thune
@copyright Microbrew.it 2015
 */

(function() {
  var http, querystring, request;

  request = require('request');

  querystring = require('querystring');

  http = (function() {
    http.prototype.endpoint = '';

    function http() {}

    http.prototype._generateUrl = function(partial) {
      if (partial == null) {
        partial = '';
      }
      return this.apiUrl + "/" + this.endpoint + "/" + partial;
    };

    http.prototype._parseParams = function(params) {
      var key, paramTuples, val;
      paramTuples = [];
      for (key in params) {
        val = params[key];
        paramTuples.push(key + "=" + val);
      }
      return paramTuples.join('&');
    };

    http.prototype._handleResponse = function(error, response, body, token, callback) {
      var e;
      if (error) {
        return callback(error, null, null, token);
      } else {
        try {
          body = JSON.parse(body);
          if (body.error) {
            callback(body.error, null, null, token);
            return;
          }
        } catch (_error) {
          e = _error;
        }
        return callback(error, response, body, token);
      }
    };

    http.prototype.authenticate = function(username, password, callback) {
      var body, postObj;
      body = {
        username: username,
        password: password,
        grant_type: "password"
      };
      if (this.clientId) {
        body.client_id = this.clientId;
      }
      postObj = {
        headers: {
          'Content-Type': 'application/x-www-form-urlencoded'
        },
        body: querystring.stringify(body),
        url: this.apiUrl + "/token"
      };
      return this.post(postObj, callback);
    };

    http.prototype.refreshToken = function(token, callback) {
      var body, postObj;
      if (!token) {
        return callback(null, null, null);
      } else {
        if (new Date().getTime() > new Date(token[".expires"]).getTime() - 30000) {
          body = {
            refresh_token: token.refresh_token,
            grant_type: "refresh_token"
          };
          if (this.clientId) {
            body.client_id = this.clientId;
          }
          postObj = {
            headers: {
              'Content-Type': 'application/x-www-form-urlencoded'
            },
            body: querystring.stringify(body),
            url: this.apiUrl + "/token"
          };
          return this.post(postObj, callback);
        } else {
          return callback(null, null, token);
        }
      }
    };

    http.prototype.post = function(query, callback, token) {
      if (token == null) {
        token = false;
      }
      return this.refreshToken(token, (function(_this) {
        return function(err, response, token) {
          var base;
          if (!query.headers) {
            query.headers = {};
          }
          if ((base = query.headers)['Content-Type'] == null) {
            base['Content-Type'] = 'application/json';
          }
          if (token != null ? token.access_token : void 0) {
            query.headers['Authorization'] = "Bearer " + token.access_token;
          }
          if (!query.url) {
            if (query.partial == null) {
              query.partial = '';
            }
            if (query.params == null) {
              query.params = {};
            }
            if (query.url == null) {
              query.url = (_this._generateUrl(query.partial)) + "?" + (_this._parseParams(query.params));
            }
            delete query.partial;
            delete query.params;
          }
          return request.post(query, function(error, response, body) {
            return _this._handleResponse(error, response, body, token, callback);
          });
        };
      })(this));
    };

    http.prototype.get = function(query, callback, token) {
      if (token == null) {
        token = false;
      }
      return this.refreshToken(token, (function(_this) {
        return function(err, response, token) {
          var base;
          if (query.body && typeof query.body === 'object') {
            query.body = JSON.stringify(query.body);
          }
          if (query.headers == null) {
            query.headers = {};
          }
          if ((base = query.headers)['Content-Type'] == null) {
            base['Content-Type'] = 'application/json';
          }
          if (token != null ? token.access_token : void 0) {
            query.headers['Authorization'] = "Bearer " + token.access_token;
          }
          if (!query.url) {
            if (query.partial == null) {
              query.partial = '';
            }
            if (query.params == null) {
              query.params = {};
            }
            if (query.url == null) {
              query.url = (_this._generateUrl(query.partial)) + "?" + (_this._parseParams(query.params));
            }
            delete query.partial;
            delete query.params;
          }
          return request.get(query, function(error, response, body) {
            return _this._handleResponse(error, response, body, token, callback);
          });
        };
      })(this));
    };

    http.prototype.put = function(query, callback, token) {
      if (token == null) {
        token = false;
      }
      if (!token) {
        return callback('Authentication required for PUT');
      }
      return this.refreshToken(token, (function(_this) {
        return function(err, response, token) {
          var base;
          if (query.body && typeof query.body === 'object') {
            query.body = JSON.stringify(query.body);
          }
          if (query.headers == null) {
            query.headers = {};
          }
          if ((base = query.headers)['Content-Type'] == null) {
            base['Content-Type'] = 'application/json';
          }
          if (token != null ? token.access_token : void 0) {
            query.headers['Authorization'] = "Bearer " + token.access_token;
          }
          if (!query.url) {
            if (query.partial == null) {
              query.partial = '';
            }
            if (query.params == null) {
              query.params = {};
            }
            if (query.url == null) {
              query.url = (_this._generateUrl(query.partial)) + "?" + (_this._parseParams(query.params));
            }
            delete query.partial;
            delete query.params;
          }
          return request.put(query, function(error, response, body) {
            return _this._handleResponse(error, response, body, token, callback);
          });
        };
      })(this));
    };

    http.prototype["delete"] = function(query, callback, token) {
      if (token == null) {
        token = false;
      }
      if (!token) {
        return callback('Authentication required for DELETE');
      }
      return this.refreshToken(token, (function(_this) {
        return function(err, response, token) {
          if (token != null ? token.access_token : void 0) {
            if (query.headers == null) {
              query.headers = {};
            }
            query.headers['Authorization'] = "Bearer " + token.access_token;
          }
          if (!query.url) {
            if (query.partial == null) {
              query.partial = '';
            }
            if (query.params == null) {
              query.params = {};
            }
            if (query.url == null) {
              query.url = (_this._generateUrl(query.partial)) + "?" + (_this._parseParams(query.params));
            }
            delete query.partial;
            delete query.params;
          }
          return request.del(query, function(error, response, body) {
            return _this._handleResponse(error, response, body, token, callback);
          });
        };
      })(this));
    };

    return http;

  })();

  module.exports = http;

}).call(this);
