// Generated by CoffeeScript 1.10.0

/*
API wrapper for origins endpoint

@author Torstein Thune
@copyright Microbrew.it 2015
 */

(function() {
  var ItemEndpoint, Origins,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  ItemEndpoint = require('./ItemEndpoint');

  Origins = (function(superClass) {
    extend(Origins, superClass);

    function Origins() {
      return Origins.__super__.constructor.apply(this, arguments);
    }

    Origins.prototype.endpoint = 'origins';

    return Origins;

  })(ItemEndpoint);

  module.exports = Origins;

}).call(this);
