// Generated by CoffeeScript 1.10.0

/*
API wrapper for other ingredients (others endpoint)

@author Torstein Thune
@copyright Microbrew.it 2015
 */

(function() {
  var ItemEndpoint, Others,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  ItemEndpoint = require('./ItemEndpoint');

  Others = (function(superClass) {
    extend(Others, superClass);

    function Others() {
      return Others.__super__.constructor.apply(this, arguments);
    }

    Others.prototype.endpoint = 'others';

    return Others;

  })(ItemEndpoint);

  module.exports = Others;

}).call(this);
