// Generated by CoffeeScript 1.10.0

/*
API wrapper for suppliers endpoint

@author Torstein Thune
@copyright Microbrew.it 2015
 */

(function() {
  var ItemEndpoint, Suppliers,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  ItemEndpoint = require('./ItemEndpoint');

  Suppliers = (function(superClass) {
    extend(Suppliers, superClass);

    function Suppliers() {
      return Suppliers.__super__.constructor.apply(this, arguments);
    }

    Suppliers.prototype.endpoint = 'suppliers';

    return Suppliers;

  })(ItemEndpoint);

  module.exports = Suppliers;

}).call(this);
