// Generated by CoffeeScript 1.10.0

/*
API wrapper for beerstyles endpoint

@author Torstein Thune
@copyright Microbrew.it 2015
 */

(function() {
  var ItemEndpoint, Users,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  ItemEndpoint = require('./ItemEndpoint');

  Users = (function(superClass) {
    extend(Users, superClass);

    function Users() {
      return Users.__super__.constructor.apply(this, arguments);
    }

    Users.prototype.endpoint = 'users';

    Users.prototype.notifications = {
      get: function(query, callback, token) {
        return callback(new Error('Not implemented'));
      },
      post: function() {
        return callback(new Error('Not implemented'));
      }
    };

    return Users;

  })(ItemEndpoint);

  module.exports = Users;

}).call(this);
