// Generated by CoffeeScript 1.9.2

/*
API wrapper for yeasts endpoint

@author Torstein Thune
@copyright Microbrew.it 2015
 */

(function() {
  var ItemEndpoint, Yeasts,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  ItemEndpoint = require('./ItemEndpoint.coffee');

  Yeasts = (function(superClass) {
    extend(Yeasts, superClass);

    function Yeasts() {
      return Yeasts.__super__.constructor.apply(this, arguments);
    }

    Yeasts.prototype.endpoint = 'yeasts';

    return Yeasts;

  })(ItemEndpoint);

  module.exports = Yeasts;

}).call(this);
