// Generated by CoffeeScript 1.10.0

/*
Microbrewit-node

Node.js library for communicating with the Microbrew.it API.

@author Torstein Thune
@copyright Microbrew.it 2015
 */

(function() {
  var acceptedInitValues, defaults, http, modules,
    indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

  http = require('./api/http');

  acceptedInitValues = ['apiUrl', 'authUrl', 'clientId', 'clientSecret'];

  defaults = {
    apiUrl: 'http://api.microbrew.it',
    authUrl: 'http://auth.microbrew.it'
  };

  modules = {
    beers: './api/beers',
    beerStyles: './api/beerstyles',
    breweries: './api/breweries',
    fermentables: './api/fermentables',
    glasses: './api/glasses',
    hops: './api/hops',
    http: './api/http',
    origins: './api/origins',
    others: './api/others',
    search: './api/search',
    suppliers: './api/suppliers',
    users: './api/users',
    yeasts: './api/yeasts',
    ingredients: './api/ingredients'
  };

  exports.init = function(config, callback) {
    var base, key, val;
    for (key in config) {
      val = config[key];
      if (indexOf.call(acceptedInitValues, key) >= 0) {
        http.prototype[key] = val;
      }
    }
    for (key in defaults) {
      val = defaults[key];
      if ((base = http.prototype)[key] == null) {
        base[key] = val;
      }
    }
    for (key in modules) {
      val = modules[key];
      this[key] = new (require(val))();
    }
    return this;
  };

}).call(this);
